### ISSUE TITLE
Django 2.X not supported

### ISSUE THREAD

**Issue by diegogm** [tokibito/django-ftpserver#17]
This package seems not compatible with Django 2.x:

`Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/site-packages/django_ftpserver/models.py", line 31, in <module>
    class FTPUserAccount(models.Model):
  File "/usr/local/lib/python3.5/site-packages/django_ftpserver/models.py", line 33, in FTPUserAccount
    get_user_model_path(), verbose_name=_("User"))
TypeError: __init__() missing 1 required positional argument: 'on_delete'
`

Since Django 2.x, on_delete is required. (Django Documentation)

**Comment by tokibito** [comment]
Thank you for the report.
I will fix this.

**Comment by tokibito** [comment]
It's fixed.
