### ISSUE TITLE
Is root user needed to run ftpserver?

### ISSUE THREAD

**Issue by tschale** [tokibito/django-ftpserver#25]
When running `manage.py ftpserver` with a non-root user I get a Permissions denied error. What directory/file is causing this? Or is a root user necessary to run the command? 

Here is the complete traceback:
```
Traceback (most recent call last):
  File "/app/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django_ftpserver/management/commands/ftpserver.py", line 147, in handle
    server = self.make_server(
  File "/usr/local/lib/python3.9/site-packages/django_ftpserver/management/commands/ftpserver.py", line 61, in make_server
    return utils.make_server(
  File "/usr/local/lib/python3.9/site-packages/django_ftpserver/utils.py", line 67, in make_server
    return server_class(host_port, handler)
  File "/usr/local/lib/python3.9/site-packages/pyftpdlib/servers.py", line 114, in __init__
    self.bind_af_unspecified(address_or_socket)
  File "/usr/local/lib/python3.9/site-packages/pyftpdlib/ioloop.py", line 1018, in bind_af_unspecified
    raise socket.error(err)
OSError: [Errno 13] Permission denied
```

**Comment by tokibito** [comment]
@tschale 
FTP server uses 21 port as default.
It is needed root permissions to use Well Known Ports(0-1024) at the Linux.
You can use root user or generally user with using other port for FTP server.

https://django-ftpserver.readthedocs.io/en/latest/management_commands.html#ftpserver

for example:
```
./manage.py ftpserver 0.0.0.0:2021
```

This command uses 2021 port for FTP server. So it does not need root user.

**Comment by tschale** [comment]
@tokibito 
Thank you for your reply! That makes totally sense. A hint in the docs could be helpful, I've added one in #27

**Comment by tschale** [comment]
@tokibito No problem, PR is updated

**Comment by tokibito** [comment]
@tschale 
Thanks for updates. I merged your PR.
